#ARITHMETIC OPERATORS
# print(100 + 40) #addition
# print(100 - 50) #subtraction
# print (100 / 2) #division that displays output in float
# print (100 % 3) #remainder
# print (100 // 2) #division that returns output in integer
# print (100 * 2) # multiplication
# print (100 ** 2) #exponontian (raise to power)

#COMPARISON OPERATORS
# print(100 == 100)
# print (100 > 90)
# print (100 >= 90)
# print (100 < 110)
# print (100 <= 10)

# #LOGICAL OPERATORS 

# print (10==10 and 20==21)
# print (20==20 or 10==55)
# print (not True)

#ASSIGNMENT OPERATORS
# x = 10
# x +=5
# print(x)

# +=
# =
# -=
# /=
# //=
# %= 
# *=

#conditional statements

name = "python"
print("False!" if name != "python" else "True!")