#print("hello, world ")

# variables
# name = "ronaldo"
# num = 7
# age = 45

#multi_assignment of variables in a single statement
name, num, age = "ronaldo", 7, 24

# get output
# print(name)
# print(num) 
# print(age) 

#printing multiple variables using one statement
# print(name, num, age)

#printing variables with other words
# print("his name is",name,"and he is",age , "years old. his jersey number is ",num )
print("his name is " + name + "and his age is " + str(age))
